// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"synchydra/internal/pkg/middleware"
	"synchydra/internal/repository"
	"synchydra/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*Migrate, func(), error) {
	db := repository.NewDB(viperViper)
	migrate := NewMigrate(db, logger)
	return migrate, func() {
	}, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewDB, middleware.NewRedis, repository.NewRepository, repository.NewUserRepository)
