// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"synchydra/internal/handler"
	"synchydra/internal/pkg/middleware"
	"synchydra/internal/repository"
	"synchydra/internal/server"
	"synchydra/internal/service"
	"synchydra/pkg/helper/sid"
	"synchydra/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*server.Server, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	sidSid := sid.NewSid()
	serviceService := service.NewService(logger, sidSid)
	db := repository.NewDB(viperViper)
	client := middleware.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	engine := server.NewServerHTTP(logger, userHandler)
	serverServer := server.NewServer(engine)
	return serverServer, func() {
	}, nil
}

// wire.go:

var middlewareSet = wire.NewSet(middleware.NewRedis, middleware.NewCanalClient, middleware.NewRocketmqProvider, middleware.NewRocketmqConsumer)

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler)
